// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQ8LcZXsyS6tLlU_k_WO4WYTGlhwxqwg',
    appId: '1:396384933688:web:54f68f7c6c674b2a4153cd',
    messagingSenderId: '396384933688',
    projectId: 'stela23-f9a52',
    databaseURL: 'https://stela23-f9a52-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'stela23-f9a52.firebaseapp.com',
    storageBucket: 'stela23-f9a52.appspot.com',
    measurementId: 'G-K976TBCJCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR7Olr9l75eipxfmUR7cwa0DkrAUGzOOc',
    appId: '1:396384933688:android:5a11646e9f15f8624153cd',
    messagingSenderId: '396384933688',
    projectId: 'stela23-f9a52',
    databaseURL: 'https://stela23-f9a52-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'stela23-f9a52.firebaseapp.com',
    storageBucket: 'stela23-f9a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZ0qRVK5UuMZ5iHmm9lglh30Gimz3P58',
    appId: '1:396384933688:ios:979751378d75377c4153cd',
    messagingSenderId: '396384933688',
    projectId: 'stela23-f9a52',
    databaseURL: 'https://stela23-f9a52-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'stela23-f9a52.firebaseapp.com',
    storageBucket: 'stela23-f9a52.appspot.com',
    iosClientId: '396384933688-tuka347ni20hk5viuikncjo2iimtepnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.stelaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZ0qRVK5UuMZ5iHmm9lglh30Gimz3P58',
    appId: '1:396384933688:ios:979751378d75377c4153cd',
    messagingSenderId: '396384933688',
    projectId: 'stela23-f9a52',
    databaseURL: 'https://stela23-f9a52-default-rtdb.asia-southeast1.firebasedatabase.app/',
    authDomain: 'stela23-f9a52.firebaseapp.com',
    storageBucket: 'stela23-f9a52.appspot.com',
    iosClientId: '396384933688-tuka347ni20hk5viuikncjo2iimtepnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.stelaApp',
  );
}
